[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#090B13"
secondaryBackgroundColor = "#111522"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
